import type { Metadata } from "next";
import TopHeaderLoggedIn from "@/app/components/sections/TopHeaderLoggedIn";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='pt-40 pb-20'>
        <TopHeaderLoggedIn />
        {children}
    </div>
  );
}
