import type { Metadata } from "next";
import TopHeaderLoggedIn from "@/app/components/sections/TopHeaderLoggedIn";
import AddShootFixed from "../components/sections/AddShootFixed";
import Toast from "../components/sections/Toast";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='pt-40 pb-30 px-4 md:px-10'>
        <TopHeaderLoggedIn />
        {children}
       
    </div>
  );
}
