import type { Metadata } from "next";
import TopHeaderPreview from "@/app/components/sections/TopHeaderPreview";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='pt-40 pb-30 px-4'>
        <TopHeaderPreview />
        {children}
       
    </div>
  );
}
